language: php
script: phpunit ./tests
php:
- 5.5
- 5.4
deploy:
  provider: heroku
  api_key:
    secure: Dcv8fTlkWYSUMufGWQRbY/0lGMcdUTyjO24Oqet4Or9fmy7yMqO+U1C90sTTJU96JGBkUKY9A6I2CZiSh5x+PKbYNTrKrvepfqfqoItveAKcHPEtgqg0glxSxtbUSR9Q6iHluJZE+XMWyRlHzFCeMoOEZQkv53FrZyngqr+CDMQ=
  app:
    master: classiques-staging
    production: classiques
